### ISSUE TITLE
Support for Binance US?

### ISSUE THREAD

**Issue by drkui** [will7200/go-crypto-sync#1]
Any chance the script will support Binance US in the future?

**Comment by will7200** [comment]
Hey @drkui 
Yup! I do plan to support it. It's next on the list. Watch for it soon.

**Comment by drkui** [comment]
Awesome, looking forward to it! 

I'm not too knowledgeable on how to use the script, are there perhaps any instructions on how to run this on Windows?

**Comment by will7200** [comment]
There isn't any instructions really. You just download from the release page https://github.com/will7200/go-crypto-sync/releases
and setup your config file (look at readme file) with the appropriate API keys.
